# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xunorus
email: info@xunorus.com
description: >
  Composer-Performer
logo: "/assets/images/xunorus_400.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://xunorus.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Xunorus'
bio: >
  I'm a composer performer from patagonia. I'm also a free and open source user and developer.
author_image: "/assets/images/xunorus_400.jpg"
twitter_username: xunorus
github_username:  xunorus


exclude: ["node_modules", "images-orig", "svg-orig", "gulpfile.js", "package.json"]

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
